### ISSUE TITLE
太酷啦！

### ISSUE THREAD

**Issue by Linaom1214** [liuzhuogood/vd-api#1]
可以增加一个访问密码设置吗？

**Comment by liuzhuogood** [comment]
可以的

**Comment by Linaom1214** [comment]
搓搓手，期待大佬更新！

**Comment by liuzhuogood** [comment]
<img width="453" alt="image" src="https://github.com/user-attachments/assets/3f1d4762-346f-4fe3-8673-f9140c7e7050">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/3d7e56b5-5931-4c37-8908-4b5bc1af5071">

已经加上访问密码

**Comment by Linaom1214** [comment]
> <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/27726662/360804605-3f1d4762-346f-4fe3-8673-f9140c7e7050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDEwNDIsIm5iZiI6MTcyNDQwMDc0MiwicGF0aCI6Ii8yNzcyNjY2Mi8zNjA4MDQ2MDUtM2YxZDQ3NjItMzQ2Zi00ZmUzLTg2NzMtZjkxNDBjN2U3MDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTc4ZWJjODc5YTY3ODU0NTQ1N2Y5MWFhYjVlMWUxOWQwY2Y2NDg1MzM0MmFmNjEzMmEyNGM3ODFjOWZlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vOGLthvPQqtLU93Jk1eu4zHv10hS1TYP--W3Js_4NpU"> <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/27726662/360804691-3d7e56b5-5931-4c37-8908-4b5bc1af5071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDEwNDIsIm5iZiI6MTcyNDQwMDc0MiwicGF0aCI6Ii8yNzcyNjY2Mi8zNjA4MDQ2OTEtM2Q3ZTU2YjUtNTkzMS00YzM3LTg5MDgtNGI1YmMxYWY1MDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTZmODkzYzk3YWE4ZWI3MjI0ODlkYmY2Mjk0ZDk2OGRlNzFiNmM0MzM0OWEyMTJjZDUzYjQ5MzI0N2NhYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnMsOn3I5ykie0R66yT1X7cm2S51zGpbyHKS3Irmv4Q">
> 已经加上访问密码

tql ！！！ Docker 也同步更新了吗？ 我去拉一个镜像试试

**Comment by liuzhuogood** [comment]
同步更新的，Github Actions自动编译的

**Comment by Linaom1214** [comment]
> 同步更新的，Github Actions自动编译的

收到
